[general]
import = ["./Monokai.toml"]


[window]
decorations = "Full"
  [window.padding]
  x = 2
  y = 1

  [window.dimensions]
  columns = 110
  lines = 38

[font]
size = 13

  [font.normal]
  family = "JetBrains Mono"

[colors]
cursor = { text = "CellBackground", cursor = "#f5a97f" }

[cursor]
thickness = 0.33

  [cursor.style]
  shape = "Beam"
  blinking = "On"
